### ISSUE TITLE
AttributeError: 'HParams' object has no attribute 'train_data_path'

### ISSUE THREAD

**Issue by SeekPoint** [lancopku/SMAE#1]
mldl@ub1604:~/ub16_prj/SMAE$ CUDA_VISIBLE_DEVICES=0 python3 main.py
INFO:tensorflow:Starting running in train mode...
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: photofacials
Traceback (most recent call last):
  File "main.py", line 327, in <module>
    tf.app.run()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 292, in main
    cnn_batcher = ClaBatcher(hps_discriminator, vocab)
  File "/home/mldl/ub16_prj/SMAE/batcher_classification.py", line 100, in __init__
    hps.train_data_path, start_file_number=0, end_file_number=65)
AttributeError: 'HParams' object has no attribute 'train_data_path'
mldl@ub1604:~/ub16_prj/SMAE$

**Comment by liuwq168** [comment]
me too

**Comment by zhangyics** [comment]
> me too

Thanks for your feedback. The bug has been fixed.
