### ISSUE TITLE
Assertion error when testing "emotional words" detection model

### ISSUE THREAD

**Issue by nickjm** [lancopku/SMAE#2]
I'm getting an error `AssertionError: Error: Empty filelist at valid_filtered/*` at the "run testing emotional words detection model" step. See the below terminal trace, including the immediately preceding log messages.

This happens when running on the default dataset included with the repo when using the given command `CUDA_VISIBLE_DEVICES=0 python3 main.py`

```
INFO:tensorflow:finished 15 epoches
INFO:tensorflow:starting run testing emotional words detection model...
INFO:tensorflow:final sigmoid attention valid acc: 0.799829
INFO:tensorflow:starting run testing emotional words detection model...
The sentiment classification accuracy of the emotional words detection model is 0.800
len valid, 164
Generating training examples......
Traceback (most recent call last):
  File "main.py", line 303, in <module>
    tf.app.run()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "main.py", line 294, in main
    batcher = GenBatcher(vocab, FLAGS) ##read from train
  File "/home/ubuntu/SMAE/Batch_iter.py", line 155, in __init__
    self.valid_queue_positive = self.fill_example_queue("valid_filtered/*", mode="valid", target_score=1, start_filenumber=0, end_filenumber=20)
  File "/home/ubuntu/SMAE/Batch_iter.py", line 239, in fill_example_queue
    assert filelist, ('Error: Empty filelist at %s' % data_path)  # check filelist isn't empty
AssertionError: Error: Empty filelist at valid_filtered/*
```

I assume these files are supposed to be written during training, but aren't for some reason. Any idea why?

**Comment by nickjm** [comment]
Update: it appears a directory `valid_test_filtered` is written instead. Is this the directory that should be used?

**Comment by zhangyics** [comment]
Yes. `valid_test_filtered` is the directory that should be used. Thanks for your feedback! The changes have been synchronized.

**Comment by zhangyics** [comment]
> Update: it appears a directory `valid_test_filtered` is written instead. Is this the directory that should be used?



> Update: it appears a directory `valid_test_filtered` is written instead. Is this the directory that should be used?

Yes. `valid_test_filtered` is the directory that should be used. Thanks for your feedback! The changes have been synchronized.
